/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package edu.austral.dissis.chess

import edu.austral.dissis.chess.app.adapter.engine.CheckerEngineImpl
import edu.austral.dissis.chess.gui.*
import javafx.application.Application
import javafx.application.Application.launch
import javafx.scene.Scene
import javafx.stage.Stage
import edu.austral.dissis.chess.app.adapter.engine.ChessEngineImpl;
import edu.austral.dissis.chess.app.factory.CapablancaFactory
import edu.austral.dissis.chess.app.factory.RegularChessFactory
import edu.austral.dissis.chess.app.factory.checkers.CheckersFactory

fun main() {
    launch(ChessGameApplication::class.java)
}

class ChessGameApplication : Application() {
    private val gameEngine =
        ChessEngineImpl(RegularChessFactory())
    private val imageResolver = CachedImageResolver(DefaultImageResolver())

    companion object {
        const val GameTitle = "Chess"
    }

    override fun start(primaryStage: Stage) {
        primaryStage.title = GameTitle

        val root = GameView(gameEngine, imageResolver)
        primaryStage.scene = Scene(root)

        primaryStage.show()
    }
}

